---
title: "Project Proposal"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, fig.height = 3)
```

## Group Antelope

## Members

**Pun Amornvivat**
**Tatchapol Jettanachai**
**Nattarach Larptaweepornsup**
**Pawin Linmaneechote**
**Chaitanya Sharma**

### Communication
We are using discord for communication.

### When can the group meet?
We all have similar time zones. So we can all meet during the evening

### Platform to communicate and share documents
Google Docs, Discord

### Question of interesr that motivated study
Acceptance rates for states depending on scores

### Topic
Admission Score for each state (might add ethnicity and income as other factors too)

### Source of data
https://collegescorecard.ed.gov/data/

### Who collected the data?
U.S Department of Education College Scoreboard

### How was the data collected?
From universities

### What are key variables in the data set, what do they measure, and how are they related to your key questions?
- States (different states in the US)
- Percentile of the ACT/SAT cumulative score for different components
- Student’s family income
- Distribution of ethnicity

### If the data may be thought of as a sample from some larger population, what is that larger population?
All of the United States of America

### Variables
- States
- SAT/ACT Scores
- Family income

### Graph
- Geo plot for visualizing the average SAT/ACT scores for each state
- Bubble chart for representing average SAT/ACT scores for each ethnicity

### Description
- Model for predicting which states students could potentially continue their studies based on their SAT and ACT scores for each subject and their family income.
- Model for predicting the average SAT/ACT acceptance score for each state depending on income

